# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/burbankai',
                'doc_host': 'https://cjgo.github.io',
                'git_url': 'https://github.com/cjgo/burbankai',
                'lib_path': 'burbankai'},
  'syms': { 'burbankai.core': { 'burbankai.core.Genome': ('core.html#genome', 'burbankai/core.py'),
                                'burbankai.core.Genome.__attrs_post_init__': ('core.html#genome.__attrs_post_init__', 'burbankai/core.py'),
                                'burbankai.core.Individual': ('core.html#individual', 'burbankai/core.py'),
                                'burbankai.core.Individual.__attrs_post_init__': ( 'core.html#individual.__attrs_post_init__',
                                                                                   'burbankai/core.py'),
                                'burbankai.core.Population': ('core.html#population', 'burbankai/core.py'),
                                'burbankai.core.create_random_founder_pop': ('core.html#create_random_founder_pop', 'burbankai/core.py'),
                                'burbankai.core.create_uniform_genetic_map': ('core.html#create_uniform_genetic_map', 'burbankai/core.py')},
            'burbankai.trait': {}}}
