# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/burbankai',
                'doc_host': 'https://cjgo.github.io',
                'git_url': 'https://github.com/cjgo/burbankai',
                'lib_path': 'burbankai'},
  'syms': {'burbankai.core': {'burbankai.core.foo': ('core.html#foo', 'burbankai/core.py')}}}
