# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/burbankai',
                'doc_host': 'https://cjgo.github.io',
                'git_url': 'https://github.com/cjgo/burbankai',
                'lib_path': 'burbankai'},
  'syms': { 'burbankai.core': {'burbankai.core.say_hello': ('core.html#say_hello', 'burbankai/core.py')},
            'burbankai.individual': { 'burbankai.individual.Individual': ('individuals.html#individual', 'burbankai/individual.py'),
                                      'burbankai.individual.Individual.allele_dosage': ( 'individuals.html#individual.allele_dosage',
                                                                                         'burbankai/individual.py')}}}
