# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_Individuals.ipynb.

# %% auto 0
__all__ = ['Individual']

# %% ../nbs/01_Individuals.ipynb 3
import attr
import torch
from fastcore.utils import patch

@attr.s(auto_attribs=True)
class Individual:
    """Represents an individual in a population."""
    haplotypes: torch.Tensor  # Shape: (ploidy, n_chromosomes, n_loci_per_chr)
    phenotype: torch.Tensor = None
    genetic_values: torch.Tensor = None
    sex: str = None
    id: int = None
    mother_id: int = None
    father_id: int = None

# %% ../nbs/01_Individuals.ipynb 4
@patch        
def allele_dosage(self:Individual):
    """Calculates the allele dosage from the haplotypes."""
    return self.haplotypes.sum(dim=0)  # Sum across the ploidy dimension to get gene/allele dosages
