# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_trait.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_trait.ipynb 2
import attr
import torch
from typing import List, Tuple, Union, Callable, Optional
