# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_crossing.ipynb.

# %% auto 0
__all__ = ['double_haploid_operation', 'make_DH', 'cross_operation', 'make_cross']

# %% ../nbs/04_crossing.ipynb 4
from .core import *
from .meiosis import *
import torch
def double_haploid_operation(gamete):
    return gamete.repeat(2, 1, 1)

def make_DH(genetic_map, individual):
    haploid_line = simulate_gametes(genetic_map, individual)
    return double_haploid_operation(haploid_line)

# %% ../nbs/04_crossing.ipynb 5
def cross_operation(egg, pollen):
    return torch.stack((egg, pollen), dim=0).squeeze(1)

def make_cross(genetic_map, mother, father):
    egg = simulate_gametes(genetic_map, mother)  # Simulating gametes for the mother
    pollen = simulate_gametes(genetic_map, father)  # Simulating gametes for the father
    return cross_operation(egg, pollen)
